---
- hosts: ios
  tasks:
  - name: "Add Static IP Address to Interface G2"
    ios_config:
      provider: "{{cli}}"
      parents:
        - "interface GigabitEthernet2"
      lines:
        - "ip address {{R2G2.IP}} {{R2G2SM.IP}}"
        - "ip access-group cloudWhiteListPolicy in"
        - "ip access-group cloudWhiteListPolicy out"
        - "no shutdown"
  - name: "Remove now moot due to VRF default static route"
    ios_config:
      provider: "{{cli}}"
      lines:
        - "no ip route 0.0.0.0 0.0.0.0 GigabitEthernet1 {{R2EEM_ROUTE_NH.IP}}"