---
- name: Configure Cloud Router
  hosts: "{{ target }}"
  vars_files:
      - "../DB/dmvpn_per_mgre_nhs_bgp_rr_address_info.yml"
      - "provider_vars/{{ cloud_provider }}.yml"
  roles:
    - "create_csr1000v_spoke_a_ha"